# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 03:25
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaraunt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formatted_address', models.CharField(blank=True, default='', max_length=100)),
                ('geometry', django.contrib.postgres.fields.jsonb.JSONField()),
                ('icon', models.URLField()),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('opening_hours', django.contrib.postgres.fields.jsonb.JSONField()),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), size=None)),
                ('place_id', models.CharField(blank=True, default='', max_length=100)),
                ('price_level', models.PositiveSmallIntegerField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('reference', models.CharField(blank=True, default='', max_length=200)),
                ('types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
            ],
        ),
    ]
