# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_auto_20170804_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaraunt',
            name='price_level',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
